#pragma once

#include "stdafx.h"


namespace Animation {

	// where animations start in Portal dat
	const DWORD BaseID = 0x03000000;

	// from ACE.Entity.Enum.MotionStance
	enum class Stance {
			Invalid              = 0x0000,
			HandCombat           = 0x003c,
			NonCombat            = 0x003d,
			SwordCombat          = 0x003e,
			BowCombat            = 0x003f,
			SwordShieldCombat    = 0x0040,
			CrossbowCombat       = 0x0041,
			UnusedCombat         = 0x0042,
			SlingCombat          = 0x0043,
			TwoHandedSwordCombat = 0x0044, // 2HandedSwordCombat
			TwoHandedStaffCombat = 0x0045, // 2HandedStaffCombat 
			DualWieldCombat      = 0x0046,
			ThrownWeaponCombat   = 0x0047,
			Graze                = 0x0048,
			Magic                = 0x0049,
			BowNoAmmo            = 0x00e8,
			CrossBowNoAmmo       = 0x00e9,
			AtlatlCombat         = 0x013b, // 138 in PY16
			ThrownShieldCombat   = 0x013c, // 139 in PY16
	};

	static Stance StanceFromID(unsigned int ID){
		return static_cast<Stance>(ID);
	}

	// adapted from ACE.Entity.Enum.MotionCommand using lowest 4 bytes only
	enum class MotionCommand {
		    // TODO: Figure out what bitfield(s) these values map to and replace with OR's
    // Note: These IDs are from the last version of the client. Earlier versions of the client had different values for some of the enums.
        Invalid                               = 0x0,
        HoldRun                               = 0x0001,
        HoldSidestep                          = 0x0002,
        Ready                                 = 0x0003,
        Stop                                  = 0x0004,
        WalkForward                           = 0x0005,
        //WalkBackwards                         = 0x0006, // doesn't exist? use negative speed?
        RunForward                            = 0x0007,
        Fallen                                = 0x0008,
        Interpolating                         = 0x0009,
        Hover                                 = 0x000a,
        On                                    = 0x000b,
        Off                                   = 0x000c,
        TurnRight                             = 0x000d,
        //TurnLeft                              = 0x000e, // doesn't exist? use negative speed?
        SideStepRight                         = 0x000f,
        //SideStepLeft                          = 0x0010, // doesn't exist? use negative speed?
        Dead                                  = 0x0011,
        Crouch                                = 0x0012,
        Sitting                               = 0x0013,
        Sleeping                              = 0x0014,
        Falling                               = 0x0015,
        Reload                                = 0x0016,
        Unload                                = 0x0017,
        Pickup                                = 0x0018,
        StoreInBackpack                       = 0x0019,
        Eat                                   = 0x001a,
        Drink                                 = 0x001b,
        Reading                               = 0x001c,
        JumpCharging                          = 0x001d,
        AimLevel                              = 0x001e,
        AimHigh15                             = 0x001f,
        AimHigh30                             = 0x0020,
        AimHigh45                             = 0x0021,
        AimHigh60                             = 0x0022,
        AimHigh75                             = 0x0023,
        AimHigh90                             = 0x0024,
        AimLow15                              = 0x0025,
        AimLow30                              = 0x0026,
        AimLow45                              = 0x0027,
        AimLow60                              = 0x0028,
        AimLow75                              = 0x0029,
        AimLow90                              = 0x002a,
        MagicBlast                            = 0x002b,
        MagicSelfHead                         = 0x002c,
        MagicSelfHeart                        = 0x002d,
        MagicBonus                            = 0x002e,
        MagicClap                             = 0x002f,
        MagicHarm                             = 0x0030,
        MagicHeal                             = 0x0031,
        MagicThrowMissile                     = 0x0032,
        MagicRecoilMissile                    = 0x0033,
        MagicPenalty                          = 0x0034,
        MagicTransfer                         = 0x0035,
        MagicVision                           = 0x0036,
        MagicEnchantItem                      = 0x0037,
        MagicPortal                           = 0x0038,
        MagicPray                             = 0x0039,
        StopTurning                           = 0x003a,
        Jump                                  = 0x003b,
        HandCombat                            = 0x003c,
        NonCombat                             = 0x003d,
        SwordCombat                           = 0x003e,
        BowCombat                             = 0x003f,
        SwordShieldCombat                     = 0x0040,
        CrossbowCombat                        = 0x0041,
        UnusedCombat                          = 0x0042,
        SlingCombat                           = 0x0043,
        TwoHandedSwordCombat                  = 0x0044,
        TwoHandedStaffCombat                  = 0x0045,
        DualWieldCombat                       = 0x0046,
        ThrownWeaponCombat                    = 0x0047,
        Graze                                 = 0x0048,
        Magic                                 = 0x0049,
        Hop                                   = 0x004a,
        Jumpup                                = 0x004b,
        Cheer                                 = 0x004c,
        ChestBeat                             = 0x004d,
        TippedLeft                            = 0x004e,
        TippedRight                           = 0x004f,
        FallDown                              = 0x0050,
        Twitch1                               = 0x0051,
        Twitch2                               = 0x0052,
        Twitch3                               = 0x0053,
        Twitch4                               = 0x0054,
        StaggerBackward                       = 0x0055,
        StaggerForward                        = 0x0056,
        Sanctuary                             = 0x0057,
        ThrustMed                             = 0x0058,
        ThrustLow                             = 0x0059,
        ThrustHigh                            = 0x005a,
        SlashHigh                             = 0x005b,
        SlashMed                              = 0x005c,
        SlashLow                              = 0x005d,
        BackhandHigh                          = 0x005e,
        BackhandMed                           = 0x005f,
        BackhandLow                           = 0x0060,
        Shoot                                 = 0x0061,
        AttackHigh1                           = 0x0062,
        AttackMed1                            = 0x0063,
        AttackLow1                            = 0x0064,
        AttackHigh2                           = 0x0065,
        AttackMed2                            = 0x0066,
        AttackLow2                            = 0x0067,
        AttackHigh3                           = 0x0068,
        AttackMed3                            = 0x0069,
        AttackLow3                            = 0x006a,
        HeadThrow                             = 0x006b,
        FistSlam                              = 0x006c,
        BreatheFlame                          = 0x006d,
        SpinAttack                            = 0x006e,
        MagicPowerUp01                        = 0x006f,
        MagicPowerUp02                        = 0x0070,
        MagicPowerUp03                        = 0x0071,
        MagicPowerUp04                        = 0x0072,
        MagicPowerUp05                        = 0x0073,
        MagicPowerUp06                        = 0x0074,
        MagicPowerUp07                        = 0x0075,
        MagicPowerUp08                        = 0x0076,
        MagicPowerUp09                        = 0x0077,
        MagicPowerUp10                        = 0x0078,
        ShakeFist                             = 0x0079,
        Beckon                                = 0x007a,
        BeSeeingYou                           = 0x007b,
        BlowKiss                              = 0x007c,
        BowDeep                               = 0x007d,
        ClapHands                             = 0x007e,
        Cry                                   = 0x007f,
        Laugh                                 = 0x0080,
        MimeEat                               = 0x0081,
        MimeDrink                             = 0x0082,
        Nod                                   = 0x0083,
        Point                                 = 0x0084,
        ShakeHead                             = 0x0085,
        Shrug                                 = 0x0086,
        Wave                                  = 0x0087,
        Akimbo                                = 0x0088,
        HeartyLaugh                           = 0x0089,
        Salute                                = 0x008a,
        ScratchHead                           = 0x008b,
        SmackHead                             = 0x008c,
        TapFoot                               = 0x008d,
        WaveHigh                              = 0x008e,
        WaveLow                               = 0x008f,
        YawnStretch                           = 0x0090,
        Cringe                                = 0x0091,
        Kneel                                 = 0x0092,
        Plead                                 = 0x0093,
        Shiver                                = 0x0094,
        Shoo                                  = 0x0095,
        Slouch                                = 0x0096,
        Spit                                  = 0x0097,
        Surrender                             = 0x0098,
        Woah                                  = 0x0099,
        Winded                                = 0x009a,
        YMCA                                  = 0x009b,
        EnterGame                             = 0x009c,
        ExitGame                              = 0x009d,
        OnCreation                            = 0x009e,
        OnDestruction                         = 0x009f,
        EnterPortal                           = 0x00a0,
        ExitPortal                            = 0x00a1,
        Cancel                                = 0x00a2,
        UseSelected                           = 0x00a3,
        AutosortSelected                      = 0x00a4,
        DropSelected                          = 0x00a5,
        GiveSelected                          = 0x00a6,
        SplitSelected                         = 0x00a7,
        ExamineSelected                       = 0x00a8,
        CreateShortcutToSelected              = 0x00a9,
        PreviousCompassItem                   = 0x00aa,
        NextCompassItem                       = 0x00ab,
        ClosestCompassItem                    = 0x00ac,
        PreviousSelection                     = 0x00ad,
        LastAttacker                          = 0x00ae,
        PreviousFellow                        = 0x00af,
        NextFellow                            = 0x00b0,
        ToggleCombat                          = 0x00b1,
        HighAttack                            = 0x00b2,
        MediumAttack                          = 0x00b3,
        LowAttack                             = 0x00b4,
        EnterChat                             = 0x00b5,
        ToggleChat                            = 0x00b6,
        SavePosition                          = 0x00b7,
        OptionsPanel                          = 0x00b8,
        ResetView                             = 0x00b9,
        CameraLeftRotate                      = 0x00ba,
        CameraRightRotate                     = 0x00bb,
        CameraRaise                           = 0x00bc,
        CameraLower                           = 0x00bd,
        CameraCloser                          = 0x00be,
        CameraFarther                         = 0x00bf,
        FloorView                             = 0x00c0,
        MouseLook                             = 0x00c1,
        PreviousItem                          = 0x00c2,
        NextItem                              = 0x00c3,
        ClosestItem                           = 0x00c4,
        ShiftView                             = 0x00c5,
        MapView                               = 0x00c6,
        AutoRun                               = 0x00c7,
        DecreasePowerSetting                  = 0x00c8,
        IncreasePowerSetting                  = 0x00c9,
        Pray                                  = 0x00ca,
        Mock                                  = 0x00cb,
        Teapot                                = 0x00cc,
        SpecialAttack1                        = 0x00cd,
        SpecialAttack2                        = 0x00ce,
        SpecialAttack3                        = 0x00cf,
        MissileAttack1                        = 0x00d0,
        MissileAttack2                        = 0x00d1,
        MissileAttack3                        = 0x00d2,
        CastSpell                             = 0x00d3,
        Flatulence                            = 0x00d4,
        FirstPersonView                       = 0x00d5,
        AllegiancePanel                       = 0x00d6,
        FellowshipPanel                       = 0x00d7,
        SpellbookPanel                        = 0x00d8,
        SpellComponentsPanel                  = 0x00d9,
        HousePanel                            = 0x00da,
        AttributesPanel                       = 0x00db,
        SkillsPanel                           = 0x00dc,
        MapPanel                              = 0x00dd,
        InventoryPanel                        = 0x00de,
        Demonet                               = 0x00df,
        UseMagicStaff                         = 0x00e0,
        UseMagicWand                          = 0x00e1,
        Blink                                 = 0x00e2,
        Bite                                  = 0x00e3,
        TwitchSubstate1                       = 0x00e4,
        TwitchSubstate2                       = 0x00e5,
        TwitchSubstate3                       = 0x00e6,
        CaptureScreenshotToFile               = 0x00e7,
        BowNoAmmo                             = 0x00e8,
        CrossBowNoAmmo                        = 0x00e9,
        ShakeFistState                        = 0x00ea,
        PrayState                             = 0x00eb,
        BowDeepState                          = 0x00ec,
        ClapHandsState                        = 0x00ed,
        CrossArmsState                        = 0x00ee,
        ShiverState                           = 0x00ef,
        PointState                            = 0x00f0,
        WaveState                             = 0x00f1,
        AkimboState                           = 0x00f2,
        SaluteState                           = 0x00f3,
        ScratchHeadState                      = 0x00f4,
        TapFootState                          = 0x00f5,
        LeanState                             = 0x00f6,
        KneelState                            = 0x00f7,
        PleadState                            = 0x00f8,
        ATOYOT                                = 0x00f9,
        SlouchState                           = 0x00fa,
        SurrenderState                        = 0x00fb,
        WoahState                             = 0x00fc,
        WindedState                           = 0x00fd,
        AutoCreateShortcuts                   = 0x00fe,
        AutoRepeatAttacks                     = 0x00ff,
        AutoTarget                            = 0x0100,
        AdvancedCombatInterface               = 0x0101,
        IgnoreAllegianceRequests              = 0x0102,
        IgnoreFellowshipRequests              = 0x0103,
        InvertMouseLook                       = 0x0104,
        LetPlayersGiveYouItems                = 0x0105,
        AutoTrackCombatTargets                = 0x0106,
        DisplayTooltips                       = 0x0107,
        AttemptToDeceivePlayers               = 0x0108,
        RunAsDefaultMovement                  = 0x0109,
        StayInChatModeAfterSend               = 0x010a,
        RightClickToMouseLook                 = 0x010b,
        VividTargetIndicator                  = 0x010c,
        SelectSelf                            = 0x010d,
        SkillHealSelf                         = 0x010e,
        //WoahDuplicate1                      = 0x010f,  // ushort collision with NextMonster?
        //MimeDrinkDuplicate1                 = 0x0110,  // ushort collision with PreviousMonster?
        //MimeDrinkDuplicate2                 = 0x0111,  // ushort collision with ClosestMonster?
        NextMonster                           = 0x010f,
        PreviousMonster                       = 0x0110,
        ClosestMonster                        = 0x0111,
        NextPlayer                            = 0x0112,
        PreviousPlayer                        = 0x0113,
        ClosestPlayer                         = 0x0114,
        SnowAngelState                        = 0x0118,
        WarmHands                             = 0x0119,
        CurtseyState                          = 0x011a,
        AFKState                              = 0x011b,
        MeditateState                         = 0x011c,
        TradePanel                            = 0x011d,
        LogOut                                = 0x011e,
        DoubleSlashLow                        = 0x011f,
        DoubleSlashMed                        = 0x0120,
        DoubleSlashHigh                       = 0x0121,
        TripleSlashLow                        = 0x0122,
        TripleSlashMed                        = 0x0123,
        TripleSlashHigh                       = 0x0124,
        DoubleThrustLow                       = 0x0125,
        DoubleThrustMed                       = 0x0126,
        DoubleThrustHigh                      = 0x0127,
        TripleThrustLow                       = 0x0128,
        TripleThrustMed                       = 0x0129,
        TripleThrustHigh                      = 0x012a,
        MagicPowerUp01Purple                  = 0x012b,
        MagicPowerUp02Purple                  = 0x012c,
        MagicPowerUp03Purple                  = 0x012d,
        MagicPowerUp04Purple                  = 0x012e,
        MagicPowerUp05Purple                  = 0x012f,
        MagicPowerUp06Purple                  = 0x0130,
        MagicPowerUp07Purple                  = 0x0131,
        MagicPowerUp08Purple                  = 0x0132,
        MagicPowerUp09Purple                  = 0x0133,
        MagicPowerUp10Purple                  = 0x0134,
        Helper                                = 0x0135,
        Pickup5                               = 0x0136,
        Pickup10                              = 0x0137,
        Pickup15                              = 0x0138,
        Pickup20                              = 0x0139,
        HouseRecall                           = 0x013a,
        AtlatlCombat                          = 0x013b,
        ThrownShieldCombat                    = 0x013c,
        SitState                              = 0x013d,
        SitCrossleggedState                   = 0x013e,
        SitBackState                          = 0x013f,
        PointLeftState                        = 0x0140,
        PointRightState                       = 0x0141,
        TalktotheHandState                    = 0x0142,
        PointDownState                        = 0x0143,
        DrudgeDanceState                      = 0x0144,
        PossumState                           = 0x0145,
        ReadState                             = 0x0146,
        ThinkerState                          = 0x0147,
        HaveASeatState                        = 0x0148,
        AtEaseState                           = 0x0149,
        NudgeLeft                             = 0x014a,
        NudgeRight                            = 0x014b,
        PointLeft                             = 0x014c,
        PointRight                            = 0x014d,
        PointDown                             = 0x014e,
        Knock                                 = 0x014f,
        ScanHorizon                           = 0x0150,
        DrudgeDance                           = 0x0151,
        HaveASeat                             = 0x0152,
        LifestoneRecall                       = 0x0153,
        CharacterOptionsPanel                 = 0x0154,
        SoundAndGraphicsPanel                 = 0x0155,
        HelpfulSpellsPanel                    = 0x0156,
        HarmfulSpellsPanel                    = 0x0157,
        CharacterInformationPanel             = 0x0158,
        LinkStatusPanel                       = 0x0159,
        VitaePanel                            = 0x015a,
        ShareFellowshipXP                     = 0x015b,
        ShareFellowshipLoot                   = 0x015c,
        AcceptCorpseLooting                   = 0x015d,
        IgnoreTradeRequests                   = 0x015e,
        DisableWeather                        = 0x015f,
        DisableHouseEffect                    = 0x0160,
        SideBySideVitals                      = 0x0161,
        ShowRadarCoordinates                  = 0x0162,
        ShowSpellDurations                    = 0x0163,
        MuteOnLosingFocus                     = 0x0164,
        Fishing                               = 0x0165,
        MarketplaceRecall                     = 0x0166,
        EnterPKLite                           = 0x0167,
        AllegianceChat                        = 0x0168,
        AutomaticallyAcceptFellowshipRequests = 0x0169,
        Reply                                 = 0x016a,
        MonarchReply                          = 0x016b,
        PatronReply                           = 0x016c,
        ToggleCraftingChanceOfSuccessDialog   = 0x016d,
        UseClosestUnopenedCorpse              = 0x016e,
        UseNextUnopenedCorpse                 = 0x016f,
        IssueSlashCommand                     = 0x0170,
        AllegianceHometownRecall              = 0x0171,
        PKArenaRecall                         = 0x0172,
        OffhandSlashHigh                      = 0x0173,
        OffhandSlashMed                       = 0x0174,
        OffhandSlashLow                       = 0x0175,
        OffhandThrustHigh                     = 0x0176,
        OffhandThrustMed                      = 0x0177,
        OffhandThrustLow                      = 0x0178,
        OffhandDoubleSlashLow                 = 0x0179,
        OffhandDoubleSlashMed                 = 0x017a,
        OffhandDoubleSlashHigh                = 0x017b,
        OffhandTripleSlashLow                 = 0x017c,
        OffhandTripleSlashMed                 = 0x017d,
        OffhandTripleSlashHigh                = 0x017e,
        OffhandDoubleThrustLow                = 0x017f,
        OffhandDoubleThrustMed                = 0x0180,
        OffhandDoubleThrustHigh               = 0x0181,
        OffhandTripleThrustLow                = 0x0182,
        OffhandTripleThrustMed                = 0x0183,
        OffhandTripleThrustHigh               = 0x0184,
        OffhandKick                           = 0x0185,
        AttackHigh4                           = 0x0186,
        AttackMed4                            = 0x0187,
        AttackLow4                            = 0x0188,
        AttackHigh5                           = 0x0189,
        AttackMed5                            = 0x018a,
        AttackLow5                            = 0x018b,
        AttackHigh6                           = 0x018c,
        AttackMed6                            = 0x018d,
        AttackLow6                            = 0x018e,
        PunchFastHigh                         = 0x018f,
        PunchFastMed                          = 0x0190,
        PunchFastLow                          = 0x0191,
        PunchSlowHigh                         = 0x0192,
        PunchSlowMed                          = 0x0193,
        PunchSlowLow                          = 0x0194,
        OffhandPunchFastHigh                  = 0x0195,
        OffhandPunchFastMed                   = 0x0196,
        OffhandPunchFastLow                   = 0x0197,
        OffhandPunchSlowHigh                  = 0x0198,
        OffhandPunchSlowMed                   = 0x0199,
        OffhandPunchSlowLow                   = 0x019a,
        WoahDuplicate2                        = 0x019b, // Appears to be the same as Motion_Woah except it starts with 0x10 instead of 0x13
	};

	static MotionCommand MotionFromID(unsigned int ID){
		return static_cast<MotionCommand>(ID);
	}


	// add ID to BaseID to get the value to look up in Portal dat file (call to OpenEntry)
	enum class ID {

		HumanStanding = 0x0001, // (human) idle/breathing
		HumanRunning = 0x0002, // (human) run
		HumanWalking = 0x0003, // (human) walk
		Unknown1 = 0x0004, // unknown
		HumanTransitionStandingToRunning1 = 0x0005, // (human) transition stopped to run (slower?)
		HumanTransitionStandingToUnknown = 0x0006, // (human) transition unknown - maybe stop to sidestep?
		HumanTransitionStandingToRunning2 = 0x0007, // (human) transition stopped to run
		HumanTransitionStandingToWalking = 0x0008, // (human) transition run to walk
		HumanTransitionUnknown = 0x0009, // (human) transition unknown - maybe stopped to walk?
		HumanTransitionWalkingToRunning = 0x000a, // (human) transition walk to run

		UnknownFrontSpin = 0x0082, // (unknown) front spin
		UnknownFrontFlip = 0x0084, // (unknown) front flip

		HumanPlaceObjectMed = 0x0093, // (human) place object at waist height

		CowTip1 = 0x0099, // (cow) tip

		CowTransitionTippedToStanding = 0x009b, // (cow) get back up from being tipped
		CowTip2 = 0x009c, // (cow) tip

		HumanClap = 0x00ab, // (human) clap
		HumanWaveArm = 0x00ac, // (human) wave
		HumanWaveHand = 0x00ad, // (human) small wave (moving hand only)

		HumanFightUnarmedWalking = 0x00c1, // (human) hand to hand combat -- walk

		HumanFightPunchLow = 0x00c5, // (human) punch low
		HumanFallOver = 0x00c6, // (human) fall over
		HumanWaveHight = 0x00c7, // (human) high wave

		UnknownRunning1 = 0x00e2, // (unknown) running 
		UnknownWalking1 = 0x00e3, // (unknown) walking

		HumanRunningHunched = 0x0237, // (human) running hunched
		HumanWalkingHunched = 0x0238, // (human) walking hunched
		HumanTransitionStandingToHunched = 0x0239, // (human) transition down to hunched/crouched
		HumanTransitionHunchedToStanding = 0x023A, // (human) transition up from hunched/crouched
		HumanTransitionHunchedUnknown1 = 0x023B, // (human) transition unknown - related to hunched/crouch
		HumanTransitionHunchedUnknown2 = 0x023C, // (human) transition unknown - related to hunched/crouch
		HumanTransitionLayingToStanding = 0x023D, // (human) transition from laying on back to standing
		HumanUnknown1 = 0x0240, // (human) not sure
		HumanPickUpFromChest = 0x0246, // (human) transition standing to low sit/crouch or pick up item out of chest?
		HumanPickUpFromGround = 0x0247, // (human) transition to pick up item off ground
		HumanPlaceObjectMedium = 0x0249, // (human) place object at neck height
		HumanPlaceObjectHigh = 0x024b, // (human) place object above head height
		HumanTransitionStandingToChairSitting = 0x024e, // (human) sit in chair
		HumanFightUnarmedSidestep = 0x0273, // (human) hand to hand combat -- sidestep left
		HumanFightArcherySidestep = 0x0293, // (human) archer combat -- sidestep left
		HumanFightShieldSidestep = 0x02f4, // (human) shield combat -- sidestep left
		HumanFightShieldWalk = 0x02fc, // (human) shield combat -- walk?
		HumanHunchedWalk = 0x0300, // (human) unknown hunched walk??
		HumanTransitionHunchedUnknown3 = 0x0301, // (human) unknown transition standing to hunched walk/run??
		ZombieWalk = 0x037d, // (human) zombie walk?
		HumanFightUnarmedTurn = 0x038b, // (human) hand to hand - shuffle feet / turn in place?
		HumanPeaceTurn = 0x038c, // (human) peace - shuffle feet / turn in place?
		HumanFightShieldTurn = 0x038d, // (human) shield combat - shuffle feet / turn in place?
		HumanLayingOnGround = 0x0397, // (human) laying on ground (breathing)
		HumanPutAway = 0x03b7, // (human) put item in backpack/back sheath?
		HumanTransitionStandingToReading = 0x03b9, // (human) transition standing to reading book?
		HumanLookingAtHeldObject = 0x03ba, // (human) reading book?
		HumanStatue1 = 0x03c0, // (human) not an animation? fixed stance for something?
		HumanLogOut = 0x03c2, // (human) log out / pledge lifestone
		HumanFalling = 0x03c8, // (human) falling through air
		HumanFallingDown = 0x0421, // (human) falling down (dying?)
		HumanTransitionPeaceToFightShield = 0x0424, // (human) transition from peace to shield combat
		HumanFightShieldStabMedium = 0x0425, // (human) shield combat - mid height stab
		HumanFightShieldIdle = 0x0426, // (human) shield combat - idle
		HumanFightShieldStabLow = 0x0427, // (human) shield combat - low stab
		HumanFightShieldStabHigh = 0x0428, // (human) shield combat - high stab
		HumanFightShieldSlashHigh = 0x042a, // (human) shield combat - high slash
		HumanFightShieldSlashMedium = 0x042b, // (human) shield combat - medium slash
		HumanFightShieldSlashLow = 0x042c, // (human) shield combat - low slash

		HumanKneel = 0x0853,
		// TODO: add more!

	};
}